# Generated by Django 3.1.4 on 2021-01-02 08:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thuonghieu',
            fields=[
                ('mathuonghieu', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('tenthuonghieu', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('masp', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tensp', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('giatien', models.IntegerField()),
                ('mota', models.CharField(max_length=1000, null=True)),
                ('sizeS', models.BooleanField(null=True)),
                ('sizeM', models.BooleanField(null=True)),
                ('sizeL', models.BooleanField(null=True)),
                ('sizeXL', models.BooleanField(null=True)),
                ('mausac', models.CharField(max_length=100)),
                ('Loai', models.CharField(choices=[('top', ' Áo'), ('bottom', 'Quần'), ('coat', 'Áo khoác')], default='Unknown', max_length=20)),
                ('rate', models.IntegerField()),
                ('soluongtonkho', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('ngaythemvao', models.DateField(default=datetime.date.today)),
                ('thuonghieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.thuonghieu')),
            ],
        ),
    ]
