# Generated by Django 3.1.4 on 2021-01-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0002_remove_products_mausac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sizeL',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sizeM',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sizeS',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sizeXL',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
