# Generated by Django 3.1.4 on 2021-01-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0003_auto_20210102_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tongrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
