# Generated by Django 3.1.4 on 2021-01-19 15:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0004_auto_20210115_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
