# Generated by Django 3.1.4 on 2021-01-02 08:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sanpham', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('stt', models.AutoField(primary_key=True, serialize=False)),
                ('ngaylapdon', models.DateField(default=datetime.date.today)),
                ('tongtien', models.IntegerField()),
                ('trangthaidonhang', models.CharField(choices=[('chuaxacnhan', 'chưa xác nhận'), ('daxacnhan', 'Đã xác nhận'), ('danggiao', 'đang giao'), ('dagiaohang', 'đã giao hàng')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('mavoucher', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phantramgiamgia', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.products')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.products')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dathang.order')),
            ],
        ),
    ]
