# Generated by Django 3.1.4 on 2021-01-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dathang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='Size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order_product',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ngaylapdon',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tongtien',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='trangthaidonhang',
            field=models.CharField(blank=True, choices=[('chuaxacnhan', 'chưa xác nhận'), ('daxacnhan', 'Đã xác nhận'), ('danggiao', 'đang giao'), ('dagiaohang', 'đã giao hàng')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='diachigiaohang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('ho', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('sdt', models.CharField(max_length=20)),
                ('diachi', models.CharField(max_length=300)),
                ('quan', models.CharField(max_length=200)),
                ('loinhan', models.CharField(max_length=500)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dathang.order')),
            ],
        ),
    ]
